const widths = [12, 5, 15, 12]
const height = 7

const all_words = [[],[6, 7, 8, 9, 16, 17, 18, 19], [3, 4, 5, 128, 129, 130, 131, 132, 133, 134, 137, 138, 139, 90, 105, 120, 135, 150], [3, 4, 5, 6, 7, 23, 35, 47, 59, 54, 55, 56, 57, 24, 25, 26, 27]];
const left_words = [[],[6, 16], [3, 128, 137], [3, 54, 24]];
const middle_words = [[],[7, 8, 17, 18], [4, 8, 129, 130, 131, 132, 133, 138, 139], [4, 5, 6, 55, 56, 25, 26]]; // words contains all but the last indices of each word
const right_words = [[],[9, 19], [5, 134, 140], [7, 57, 27]];
const top_words = [[],[], [90], [23]]
const vert_middle_words = [[],[], [105, 120, 135], [35, 47]]
const bottom_words = [[],[], [150], [59]]

const answer = [
  [],
  [
    "P",
    "null",
    "null",
    "S",
    "null",
    "A",
    "G",
    "E",
    "N",
    "T",
    "N",
    "null",
    "R",
    "U",
    "E",
    "I",
    "M",
    "A",
    "G",
    "E",
    "C",
    "null",
    "null",
    "null",
    "null",
    "S",
    "null",
    "null",
    "null",
    "null",
  ],
  [
    "null",
    "null",
    "S",
    "L",
    "A",
    "B",
    "null",
    "C",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "P",
    "null",
    "S",
    "null",
    "null",
    "L",
    "A",
    "N",
    "G",
    "U",
    "A",
    "G",
    "E",
    "null",
    "H",
    "O",
    "U",
    "S",
    "E",
    "null",
    "A",
    "null",
    "null",
    "null",
    "null",
    "R",
    "null",
    "null",
    "null",
    "null",
    "R",
    "null",
    "I",
    "null",
    "null",
    "S",
    "C",
    "I",
    "E",
    "N",
    "C",
    "E",
    "null",
    "H",
    "null",
    "T",
    "I",
    "G",
    "E",
    "R",
    "S",
    "null",
    "null",
    "N",
    "null",
    "H",
    "null",
    "H",
    "I",
    "D",
    "S",
    "null",
    "N",
    "null",
    "null",
    "null",
    "null",
    "null",
    "G",
    "null",
    "null",
    "null",
    "E",
    "S",
    "null",
    "null",
    "null",
    "M",
    "A",
    "T",
    "H",
    "null",
    "null",
    "L",
    "null",
    "null",
    "null",
    "L",
    "T",
    "I",
    "M",
    "B",
    "E",
    "R",
    "null",
    "I",
    "null",
    "null",
    "I",
    "null",
    "null",
    "null",
    "E",
    "O",
    "null",
    "null",
    "I",
    "N",
    "T",
    "E",
    "R",
    "S",
    "E",
    "S",
    "S",
    "I",
    "O",
    "N",
    "R",
    "O",
    "B",
    "O",
    "T",
    "S",
    "null",
    "E",
    "null",
    "null",
    "H",
    "null",
    "null",
    "null",
    "null",
    "Y",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "D",
    "T",
    "W",
    "null",
    "null",
    "null",
    "null",
    "null",
  ], ['V', 'null', 'null', 'S', 'T', 'A', 'R', 'T', 'U', 'P', 'null', 'C', 'E', 'R', 'A', 'null', 'H', 'I', 'null', 'null', 'null', 'null', 'null', 'L', 'N', 'U', 'M', 'B', 'E', 'R', 'S', 'null', 'P', 'U', 'R', 'E', 'T', 'I', 'P', 'null', 'null', 'D', 'O', 'M', 'E', 'S', 'null', 'A', 'U', 'N', 'null', 'A', 'I', 'R', 'L', 'I', 'N', 'E', 'null', 'N', 'R', 'null', 'null', 'null', 'C', 'O', 'A', 'L', 'null', 'null', 'null', 'E', 'E', 'N', 'T', 'R', 'E', 'P', 'R', 'E', 'N', 'E', 'U', 'R']
];

let test_board = []
for (let i = 0; i < height*widths[0]; i++) {
  test_board.push("Q")
}

answer[0] = test_board

const starting_letters_ind = [
  [],
  [0, 3, 6, 13, 15, 16, 19, 25],
  [3, 19, 25, 32, 49, 52, 62, 65, 72, 60, 75, 85, 95, 97, 104, 107, 120, 123, 130, 137, 157],
  [0, 4, 5, 8, 9, 14, 20, 23, 25, 30, 32, 38, 41, 45, 47, 48, 49, 52, 55, 59, 64, 67, 72, 75, 81, 82]
];

export {answer, starting_letters_ind, all_words, left_words, middle_words, right_words, widths, top_words, vert_middle_words, bottom_words}